local PetData = {
    {
        Id = "solar_panel",
        Name = "Solar Panel",
        Rarity = "Common",
        Cost = 25,
        EnergyPerSecond = 0.6,
        ClickBoost = 0.4,
        AreaRequired = 1,
        Icon = "☀️",
        Description = "Small but steady energy production.",
    },
    {
        Id = "hand_crank",
        Name = "Hand Crank",
        Rarity = "Common",
        Cost = 90,
        EnergyPerSecond = 1.4,
        ClickBoost = 0.9,
        AreaRequired = 1,
        Icon = "⚙️",
        Description = "A reliable portable generator.",
    },
    {
        Id = "wind_turbine",
        Name = "Wind Turbine",
        Rarity = "Uncommon",
        Cost = 250,
        EnergyPerSecond = 3.5,
        ClickBoost = 1.8,
        AreaRequired = 2,
        Icon = "🌀",
        Description = "Captures air currents for strong output.",
    },
    {
        Id = "geothermal_core",
        Name = "Geothermal Core",
        Rarity = "Uncommon",
        Cost = 700,
        EnergyPerSecond = 7,
        ClickBoost = 3.2,
        AreaRequired = 2,
        Icon = "🌋",
        Description = "Harnesses subterranean heat.",
    },
    {
        Id = "fusion_cell",
        Name = "Fusion Cell",
        Rarity = "Rare",
        Cost = 1800,
        EnergyPerSecond = 16,
        ClickBoost = 7,
        AreaRequired = 3,
        Icon = "🔥",
        Description = "Compact fusion energy source.",
    },
    {
        Id = "particle_accelerator",
        Name = "Particle Accelerator",
        Rarity = "Rare",
        Cost = 5000,
        EnergyPerSecond = 36,
        ClickBoost = 14,
        AreaRequired = 3,
        Icon = "⚡",
        Description = "Accelerates matter into strong power output.",
    },
    {
        Id = "dyson_sphere",
        Name = "Dyson Sphere",
        Rarity = "Epic",
        Cost = 13000,
        EnergyPerSecond = 80,
        ClickBoost = 28,
        AreaRequired = 4,
        Icon = "🪐",
        Description = "Harvests the energy of a star.",
    },
    {
        Id = "black_hole_synthesizer",
        Name = "Black Hole Synthesizer",
        Rarity = "Legendary",
        Cost = 36000,
        EnergyPerSecond = 180,
        ClickBoost = 60,
        AreaRequired = 4,
        Icon = "🕳️",
        Description = "Creates controlled singularity energy.",
    },
    {
        Id = "quantum_reactor",
        Name = "Quantum Reactor",
        Rarity = "Mythic",
        Cost = 85000,
        EnergyPerSecond = 420,
        ClickBoost = 140,
        AreaRequired = 4,
        Icon = "🌌",
        Description = "A final frontier of energy generation.",
    },
}

return PetData
